DROP TABLE IF EXISTS list;
CREATE TABLE list (name TEXT, value INT, image TEXT);
INSERT INTO list VALUES ('Apple'		, 10	, 'img-apple.png'		);
INSERT INTO list VALUES ('Blueberry'	, 100	, 'img-blueberry.png'		);
INSERT INTO list VALUES ('Cherry'		, 30	, 'img-cherry.png'		);
INSERT INTO list VALUES ('Grapes'		, 70	, 'img-grapes.png'		);
INSERT INTO list VALUES ('Lemon'		, 3		, 'img-lemon.png'		);
INSERT INTO list VALUES ('Orange'		, 5		, 'img-orange.png'		);
INSERT INTO list VALUES ('Pear	'		, 7		, 'img-pear.png'		);
INSERT INTO list VALUES ('Raspberry'	, 25	, 'img-raspberry.png'		);
INSERT INTO list VALUES ('Starwberry'	, 40	, 'img-starwberry.png'		);
